# Generated by Django 4.0.5 on 2022-06-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(default=None, max_length=75, null=True, verbose_name='Имя автора')),
                ('text_comment', models.TextField(null=True, verbose_name='Новость')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=75, null=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250, null=True, verbose_name='Новость')),
                ('description', models.TextField(null=True, verbose_name='Новость')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(verbose_name='Дата изменения')),
                ('activate', models.BooleanField(verbose_name='Опубликовано')),
                ('category', models.CharField(choices=[('Power', 'Власть'), ('Economy', 'Экономика'), ('regions', 'В регионах'), ('world', 'В мире'), ('Incidents', 'Происшествия'), ('Society', 'Общество'), ('Sport', 'Спорт'), ('culture', 'Культура')], default=None, max_length=10, null=True, verbose_name='Катерогия')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news_app.comments', verbose_name='Автор')),
                ('label', models.ManyToManyField(to='news_app.label', verbose_name='Теги')),
            ],
        ),
    ]
